### ISSUE TITLE
Twenty Twenty Four: User Support Guide

### ISSUE THREAD

**Issue by jordesign** [WordPress/Documentation-Issue-Tracker#1100]
## What is the new page you are requesting?

A user guide for the Twenty Twenty-Three theme and its style variations.

## How will this new page help you?

With a new default theme coming with WordPress 6.4, users will find a getting-started guide helpful. It could include information like:

* How Twenty Twenty-Four works with the Site Editor, including what templates and patterns are included
* How style variations work and what the included style variations look like
* How to make common customizations
* An overview of some of the features in TT4 that take advantage of WP 6.4 improvements

In terms of the format, we can draw inspiration from this existing guide for TT2:
https://wordpress.org/documentation/article/twenty-twenty-three/

## Specific features to highlight/explain

[ ] Home template switching
[ ] Style Variations
[ ] Patterns
[ ]Aspect Ratio on Placeholders?
[ ] Asterix Style Variation for headings
[ ] Vertical Text (on RSVP pattern)

## General

[ ] Make sure all screenshots are relevant to the latest version
[ ] Make sure videos are up to date, if any
[ ] Add ALT tags for the images
[ ] Make sure the headings are in sentence case
[ ] Convert all reusable blocks to a ‘regular block’.

**Comment by jordesign** [comment]
I'm happy to be assigned this one...

**Comment by jordesign** [comment]
Hey @nouman17610 I'm also happy to work on/help out with this one - let me know how it's all going 👍

**Comment by jordesign** [comment]
I've started a draft of this document - based on the one from Twenty Twenty Three last year. I'll be filling it out with details as they get finalised in the theme itself.

**Comment by MaggieCabrera** [comment]
Hey, thanks for tackling this issue! Some comments:


- Home template switching

Not just the home can be replaced. We added full page patterns for the Home, Index, Archive and Search pages, as well as the single for post and pages. That's why we have so many patterns, some will only show up on the template switching/creation flows.

- Aspect Ratio on Placeholders?

Probably the most prominent use of this is in the gallery-offset-images-grid-3/4-col patterns, but it's all over the patterns in general. Also the Team pattern. The use of placeholders is generally new

- Asterix Style Variation for headings

This block style will not work on firefox if the heading is empty, to disuade users from just trying to add the asterisk without adding text and leaving an empty heading (chrome doesn't support the distinction). I don't know if this should be mentioned at all in this context, though.

- Patterns loaded from the directory! 

this one will probably be missed by many people if they don't look into the code. On theme.json we are loading two patterns directly from the directory without adding the code in the theme:

```
	"patterns": [
		"three-columns-of-services",
		"clients-section"
	]

```

**Comment by jordesign** [comment]
Thanks @MaggieCabrera, 

> Not just the home can be replaced. We added full page patterns for the Home, Index, Archive and Search pages, as well as the single for post and pages. That's why we have so many patterns, some will only show up on the template switching/creation flows.

Perfect- thank you. I'd love your input as to whether this drafted text is accurate? And that I'm referring to the variant designs/layouts in the correct way.

---

## One theme, many variations

In the past, default themes often centered around a specific topic or style. However, Twenty Twenty-Four breaks away from this tradition. This theme is thoughtfully designed to be your all-encompassing choice for any type of website, regardless of its specific focus

![TT4 Post - Image 2](https://github.com/WordPress/Documentation-Issue-Tracker/assets/1842363/6f145b91-aa20-4f70-aa87-4ecf2235463c)

Twenty Twenty-Four ships with 2 additional theme variations - Twenty Twenty-Four Writer and Twenty Twenty-Four Portfolio.

### Alternate Templates

Twenty Twenty-Four comes with alternate designs (in the 'Writer' and 'Portfolio' variant layouts) for the following templates:

* Blog Home
* Index
* Archive
* Search

You can use the Replace Template functionality [linked to support doc] to switch to a variant when editing the template.
[video]

```

**Comment by MaggieCabrera** [comment]
I'm not sure about the wording about variations, since we usually use the word for theme variations, which generally change the sites styling (colors, fonts, spacing, etc). I would say we provide alternative templates to fit 3 different types of websites (business, portfolio, blogging), with the business being the default one and the alternatives being provided via patterns. @beafialho might be able to put this better into words?

The template switching flow was introduced into 6.4 by https://github.com/WordPress/gutenberg/pull/54609, and I'm not sure how that will be documented for 6.4!

**Comment by jordesign** [comment]
> The template switching flow was introduced into 6.4 by https://github.com/WordPress/gutenberg/pull/54609, and I'm not sure how that will be documented for 6.4!

This should be covered by https://github.com/WordPress/Documentation-Issue-Tracker/issues/1202 thankfully

**Comment by MaggieCabrera** [comment]
no, I don't think so! the PR they mention only works for pages, the one I mention works for any template

**Comment by jordesign** [comment]
@MaggieCabrera  Ah thank you - I'll make sure that gets included.

**Comment by jordesign** [comment]
Closing this out - as it is being covered in #1234
