### ISSUE TITLE
[HelpHub] Heading Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#123]
Article: https://wordpress.org/support/article/heading-block/

## Updating for 5.7
- [ ] Allow adding a header by typing /h1, /h2 etc. - [26597](https://github.com/WordPress/gutenberg/pull/26597)
- [ ] add wide and full width options - [25917](https://github.com/WordPress/gutenberg/pull/25917)

## General
- [ ] make sure all screenshots are relevant for current version (5.9)
- [ ] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/rVJjBIGh/2-heading-block

**Comment by hannaw93** [comment]
In progress :)

**Comment by hannaw93** [comment]
All is complete except updating screenshots. Since I can't add them directly, I will upload them here to make further editing easier: 
<img width="748" alt="Block Toolbar" src="https://user-images.githubusercontent.com/48948921/152535886-5ccd55d0-8200-4a8a-9d1e-320c8d28cb12.png">
<img width="779" alt="Heading block can be transformed to a Paragraph, Columns, Group, List, Quote or a Pullquote" src="https://user-images.githubusercontent.com/48948921/152535903-b107d783-5045-42d7-a5cb-726c0758d447.png">
<img width="661" alt="Align Options" src="https://user-images.githubusercontent.com/48948921/152535920-d613cb
<img width="587" alt="All heading tags" src="https://user-images.githubusercontent.com/48948921/152535927-13030f44-f5c3-4dd7-94f2-3f63bf513574.png">
01-a681-4de8-9052-6a8077269657.png">

**Comment by zzap** [comment]
Thank you

**Comment by AndreeaCristinaRadacina** [comment]
Here are the updated screenshots:
The tags appear differently:
<img width="496" alt="01_HeadingBlock_tags" src="https://user-images.githubusercontent.com/86592992/171644246-9f7d2e77-9f55-45ee-a713-abba28b2f61e.png">
There are some new editing options - highlight, keyboard input 
<img width="510" alt="02_HeadingBlock_moreeditingoptions" src="https://user-images.githubusercontent.com/86592992/171644256-b8aa3f18-7de2-4896-9e10-e22c2be3fb91.png">
There are extra options - Lock and the Reusable icon has changed.
<img width="275" alt="03_HeadingBlock_moreoptions" src="https://user-images.githubusercontent.com/86592992/171644268-6064853c-a959-4e2e-9507-c8988667d2c0.png">
The heading settings contain the Dimensions now, and their order has changed:
<img width="275" alt="04_HeadingBlock_headingsettings" src="https://user-images.githubusercontent.com/86592992/171644276-0a92c7be-5699-44c0-a3d7-fb3b676e9199.png">
The advanced tab looks differently now:
<img width="280" alt="06_HeadingBlock_advanced" src="https://user-images.githubusercontent.com/86592992/171645112-609cb26e-b879-41e0-849f-c906c0245931.png">
The dimensions option:
<img width="280" alt="05_HeadingBlock_newoption" src="https://user-images.githubusercontent.com/86592992/171645121-77ffdbef-f9b9-48ed-956e-2b0943d9fe1a.png">
