### ISSUE TITLE
Link error on Developer Resources

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/Documentation-Issue-Tracker#1402]
## Issue Description

On developer Resources page (eg: https://developer.wordpress.org/block-editor/how-to-guides/), on the very bottom, after the content section, "Edit the article on Github links", doesn't work. It simply reloads the same page. 

![image](https://github.com/WordPress/Documentation-Issue-Tracker/assets/33965848/5e86a5ad-a268-4b1f-a5ae-118bf1a79b28)

Most of the articles on Block Editor Handbook has this issue, probably using the same template.

## URL of the Page with the Issue

https://developer.wordpress.org/block-editor

## Why is this a problem?

Link issue. Supposed to take the person to Github page of the documentation.

## Suggested Fix

Update Link

**Comment by adamwoodnz** [comment]
Thanks for raising, this is a duplicate of https://github.com/WordPress/wporg-developer/issues/438

**Comment by ndiego** [comment]
This is now fixed https://github.com/WordPress/wporg-developer/pull/472.

**Comment by flexseth** [comment]
@alanjacobmathew greetings! In order to edit pages in the Devhub (developer.wordpress.org) one has to build the developer documentation locally, which then shows the link to edit the handbook. This is a guard rail to limit the number of edits made to the handbook, I'd imagine. 

As @ndiego mentioned, if you're logged into the Devhub (only certain members have access in this way) - it's directly editable. But for this particular handbook (the WordPress Plugins Handbook) the link is no longer there unless the editor has been given access to the handbook which resides on an actual WP installation. 

Hopefully this provides some information as to why the link is not there. I'm going to close this issue, happy to answer any other questions you may have. 

Best/Seth
