### ISSUE TITLE
[HelpHub] First Steps with WordPress

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#143]
Article: https://wordpress.org/support/article/first-steps-with-wordpress/

## General
- [x] make sure all screenshots/videos are relevant for current version (5.9)
- [x] update changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/0oQYPV6P/87-wordpress-lessons

**Comment by agnieszkaszuba** [comment]
I'd like to take this issue :)

**Comment by agnieszkaszuba** [comment]
Actually I couldn't see any screenshots that are not up to date for 5.9 😅 So unless I missed them maybe there aren't any that need to be update in this article.

**Comment by atachibana** [comment]
@agnieszkaszuba 
As you see, there are no big differences between 5.9 and previous versions, but some exist:

- Log In: 5.9 login panel has the language selector at the bottom.
- Test Drive Your WordPress Site: 5.9 default theme is Twenty Twenty-two.
- Changing the Look: 5.9 will list Twenty Twenty-two.
- Creating a post: Twenty Twenty-two will show us different editor view.

**Comment by mileamadalin** [comment]
I come here with some new screenshots for the 6.0 WordPress version. I hope I'm in the right place. 😅 

The first image, "01. login," is identical, so there is no change. 

02. Start at the Top (Dashboard). We can also use the same one for the image "04. Test Drive the WordPress Administration Screens" since seems to be the same. 

<img width="1440" alt="02_First Steps with WordPress_Dashboard" src="https://user-images.githubusercontent.com/6906834/171617693-2bd868da-6dda-42a2-a3a8-d023b380b481.png">

Also, here in the paragraph, we need to change "Twenty Twenty-One" with "Twenty Twenty-Two."
"Test Drive Your WordPress Site(https://wordpress.org/support/article/first-steps-with-wordpress/#test-drive-your-wordpress-site)

Take time to look at the site before you get into changing it and figuring out [how it all works]. It’s important to see how the WordPress ~Twenty Twenty-One~ Twenty Twenty-Two theme is laid out and how it works. Consider this the test drive before adding all the special features."

"03. Test Drive Your WordPress Site" image, no change.

**Comment by atachibana** [comment]
@mileamadalin 

Great Work!
I enhanced all your suggestions to the page.
https://wordpress.org/support/article/first-steps-with-wordpress/
