### ISSUE TITLE
[6.6 HelpHub] Browse and switch templates and template parts in the Inspector

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Documentation-Issue-Tracker#1614]
Draft
Article: https://wordpress.org/documentation/article/template-part-block/

## Update for 6.6
- [x] [[Template inspector: Surface related patterns]](https://github.com/WordPress/gutenberg/pull/55091)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by atachibana** [comment]
(update below section)

## Replacing one template part with another

If the theme has more than one template part for the same area, you will see a pattern selector in the template inspector panel. If you don’t see this selector, this is because the theme hasn’t provided multiple template parts for the same area.

https://github.com/user-attachments/assets/83261526-f3aa-4900-9d29-a958d5554ee5

**Comment by Leonardus-Nugraha** [comment]
I would suggest rephrasing a little bit to:

"If the theme has more than one _patterns_ for the same template part area, you will see a pattern selector in the template inspector panel. If you don’t see this selector, this is because the theme hasn’t provided multiple _patterns_ for the same area."

Because if I understand correctly, it's the pattern that has multiple options, not the template part

**Comment by atachibana** [comment]
@Leonardus-Nugraha Thank you for pointing that out. You are right. I have reflected your suggestion on the page.
https://wordpress.org/documentation/article/template-part-block/
The issue is closed.
