### ISSUE TITLE
[HelpHub] Flickr Block

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#164]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/flickr-embed/

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/eQG0bUJ9/19-flickr-block-embeds

**Comment by marinakoleva** [comment]
I'll try to add some updated screenshots.

**Comment by marinakoleva** [comment]
Note: not every screenshot needed to be updated. Also, photo and screenshot from Flickr updated, so that they are consistent across the post (couldn't find the previous penguin 😿 ).

*** Embedded image from flickr**
<img width="1063" alt="Screenshot 2022-09-14 at 13 38 32" src="https://user-images.githubusercontent.com/90325221/190154919-b125eb9b-ec0f-4481-9d57-b02d93906c9e.png">
* **Find your photo or video on Flickr.com, and copy the URL of the photo, album, gallery or video from the browser bar.**
<img width="1841" alt="Screenshot 2022-09-14 at 13 38 19" src="https://user-images.githubusercontent.com/90325221/190156884-5cbe5a37-c02b-47ac-8400-582a6757f9ef.png">
* **Add Flickr embed block to your post or page**
<img width="234" alt="Screenshot 2022-09-14 at 13 17 22" src="https://user-images.githubusercontent.com/90325221/190155321-710155b9-37d4-4fb8-9bfb-4820a206fd07.png">
* **If the link can be successfully embedded into the post/page, you will see the preview in your block editor.**
<img width="666" alt="Screenshot 2022-09-14 at 13 31 06" src="https://user-images.githubusercontent.com/90325221/190155837-ea741be7-d9aa-40e2-b6f7-5be4ace59ec3.png">
* **Embed Photo Album and Gallery**
Note: the current behaviour doesn't seem to match the screenshot, as no matter the orientation of the photos, you can’t see both arrows at the same time.
<img width="677" alt="Screenshot 2022-09-14 at 14 12 20" src="https://user-images.githubusercontent.com/90325221/190156324-57c39929-bbca-4993-8d98-97e26ce6b1e5.png">
* **Block Toolbar**
<img width="666" alt="Screenshot 2022-09-14 at 13 31 06" src="https://user-images.githubusercontent.com/90325221/190157765-52ec6fcc-57d9-4f2c-99f5-ab950c3b278f.png">
_Description of the new Toolbar:_
The Block Toolbar for the Flickr embed shows six buttons:
* Embed: Change block type or style
* Drag
* Move down
* Change alignment
* Edit URL
* Options
* **Transform to:**
<img width="361" alt="Screenshot 2022-09-14 at 14 28 18" src="https://user-images.githubusercontent.com/90325221/190158322-802e78d8-7c51-40f9-b65c-9250c1bf4f4e.png">

**Comment by marinakoleva** [comment]
Github refused to apply my formatting, sorry!

**Comment by femkreations** [comment]
Thanks @marinakoleva  This content looks great. We will add this to the article.

**Comment by samxmunoz** [comment]
I'll update this article.

**Comment by samxmunoz** [comment]
@zzap and @femkreations - this is **Ready for review!!!**

**Comment by zzap** [comment]
Reviewed. Great work @marinakoleva and @samxmunoz , thank you both very much.

**Comment by zzap** [comment]
I just edited `Changelog` heading to be level 2 (and set font size smaller) so that it doesn't appear as subheading for `Block Settings`.
