### ISSUE TITLE
[HelpHub] Kickstarter

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#172]
Quick video overview of how to contribute this change (with English subtitles): https://wordpress.tv/2022/03/04/update-screenshots-in-wordpress-documentation/

Original article: https://wordpress.org/support/article/kickstarter-embed/

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are up to date
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

Issue migrated from Trello: https://trello.com/c/REZB1Fhm/20-kickstarter

**Comment by LizaBogatyrev** [comment]
Assign this to me please :)

**Comment by LizaBogatyrev** [comment]
Make sure all screenshots are relevant for the current version (6.0) 
- found a few screenshots that could use an update.  See attached 
find Kickstarter project - share button and options have been updated on Kickstarter
![KickstarterProject](https://user-images.githubusercontent.com/113512233/190143517-e71e8c26-d3b9-4f58-a0af-1076185e813b.png)
Create short link
![KickstarterEmbed](https://user-images.githubusercontent.com/113512233/190144113-e751fd55-ec34-4912-b2a0-979edb053d91.png)
![KickstarterGetShortLink](https://user-images.githubusercontent.com/113512233/190144482-7124d0a9-5404-4767-95a8-fc7ccc7f26bd.png)
Embed block - embed blocks have been added and changed position since the article was last updated. 
![EmbedBlockKickstarter](https://user-images.githubusercontent.com/113512233/190140940-575488eb-ba0e-466d-9ad8-88c7277f4fa4.png)
The embed block view is the same, but i've updated it to reflect the new project link.

Successful embed
![SuccessfulEmbed](https://user-images.githubusercontent.com/113512233/190145964-784eeec4-6a0f-4942-a90c-94e86a41c02b.png)

Failed embed
![failedEmbed](https://user-images.githubusercontent.com/113512233/190147876-8a8f9884-9f59-42f1-8396-b3cb011d5b93.png)

Block toolbar
![KickstarterBlockTools](https://user-images.githubusercontent.com/113512233/190148041-4b98700b-8292-4ecd-9d5f-a6d397aba1bc.png)

Transform to Group - color and background changes

![KickstarterGroup](https://user-images.githubusercontent.com/113512233/190149437-dcecc11c-3ce1-42a0-912d-063dad5ed147.png)

Change width
![ChangeWidthKickstarter ](https://user-images.githubusercontent.com/113512233/190149945-0fd42fad-3095-4048-a44f-31f6f59d6ea8.png)

Make sure videos are up to date 

There are no videos in this article

 Make sure the headings are in sentence case

 - Headings are in sentence case
 - 
 Update the changelog at the end of the article

**Comment by LizaBogatyrev** [comment]
Changelog: 
Updated 2022-09-14
Updated 6.0 screenshots

**Comment by LizaBogatyrev** [comment]
@zzap Please review the changes

**Comment by femkreations** [comment]
Thanks @LizaBogatyrev  This content looks great. Thank you for your work. We will add this to the article.

**Comment by samxmunoz** [comment]
I'll be updating this article.

**Comment by samxmunoz** [comment]
@femkreations / @zzap - this one is READY FOR REVIEW!!! 🎉 💃🏼

**Comment by zzap** [comment]
Reviewed, great work @samxmunoz and @LizaBogatyrev. Thank you for adding alt for media files @samxmunoz

**Comment by zzap** [comment]
I just edited `Changelog` heading to be level 2 (and set font size smaller) so that it doesn't appear as subheading for `Block Settings`.
