### ISSUE TITLE
Plugin Handbook custom meta boxes incorrect AJAX server side code

### ISSUE THREAD

**Issue by atachibana** [WordPress/Documentation-Issue-Tracker#18]
This issue was moved from [HelpHub issue #315](https://github.com/WordPress/HelpHub/issues/315) originally reported by [ribaricplusplus](https://github.com/ribaricplusplus).

<hr />

Hello,

I think [this](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/#server-side-code) server side code is incorrect. It's supposed to be handling the AJAX request, yet it seems to be enqueueing JavaScript.

**Comment by leogermani** [comment]
Fixed. The examples don't look great and we can consider if we want to keep that ajax approach in the docs still... any opinions?

**Comment by theMikeD** [comment]
I think we keep the ajax concept even if the examples need refinement

**Comment by leogermani** [comment]
I don't know at what point it was decided to make the examples really simple and without any sanitization, permission checks, usage of nonces and etc. This is noted in the page as being intentional but I'm not sure it's the best decision... but if this is consistent across all devhub, it's difficult to change it now

**Comment by theMikeD** [comment]
Agreed. All examples should be best practice including phpcs formatting. It's in my overall plan.

**Comment by theMikeD** [comment]
Closing this since the original issue was handled. The fact that code examples don't conform to WP code standards or any of the items mentioned by leogermani is another issue.
