### ISSUE TITLE
[HelpHub] Next Post

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#238]
## What is the new page you are requesting?

New article required for the Next Post block

## New page 
- [ ] Create a new article for the Next Post  block 
- [ ] Make sure the URL slug under Permalink is: next-post-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [ ] Convert all reusable blocks to a ‘regular block’.

## Update for 6.2
- [ ] Add arrows to post navigation link [40684](https://github.com/WordPress/gutenberg/pull/40684)

## Update for 6.1
- [ ] Post Navigation Link: add design controls  [41378](https://github.com/WordPress/gutenberg/pull/41378)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos are up to date
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by blogsmithteam** [comment]
I'll take this one too if available! @femkreations

**Comment by femkreations** [comment]
@blogsmithteam Assigned to you. Let me know if you still want to work on this one as well.

**Comment by femkreations** [comment]
## Notes
1. We are not adding detailed updates for the Block settings as we are revamping the block settings for all the block articles 
2. Some of the PRs for 6.1 have great videos that can be added to the article (even for the Block settings section)

**Comment by zzap** [comment]
A quick guideline https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/guides/new-article-block-editor.md

**Comment by dottxado** [comment]
I'm picking this up 😄

**Comment by zzap** [comment]
#240 is related, and @pls78 (across the table) is working on it so you can, maybe, compare notes and help each other.

**Comment by dottxado** [comment]
The _next post block_ displays a customizable link to the next post published in the same post type.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/23632632/232006775-9d92a074-43f3-48a2-a9fe-37bcad024a46.png">

In order to add a **Next post** block, click on the Add block button and select the **Next post** block.

You can also type `/next` in a new paragraph and hit enter.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/23632632/232007250-eddc4341-0e96-4ace-96e4-26f2205a26d8.png">

## Block toolbar
The **Next post** block toolbar shows 6 buttons:
- Change block type or style
- Moving handles
- Align text
- Bold formatting
- Italic formatting
- More options
<img width="307" alt="image" src="https://user-images.githubusercontent.com/23632632/232008594-ee14266e-ff9f-4fee-9cae-91bd4d361d6f.png">

### Change block type or style
<img width="326" alt="Schermata 2023-04-14 alle 11 44 27" src="https://user-images.githubusercontent.com/23632632/232010950-546ba7f7-1afa-44a8-9066-f178f1dcf2b2.png">
You can transform the **Next post** block into the **[Columns](https://wordpress.org/documentation/article/columns-block/)** block and the **[Group](https://wordpress.org/documentation/article/group-block/)** block. Refer to their documentation to know more.

### Moving handles
<img width="303" alt="Schermata 2023-04-14 alle 12 03 15" src="https://user-images.githubusercontent.com/23632632/232015180-250481e4-9226-4bd3-b94a-8706508f15a5.png">
Use the arrows on the right to move up or down the block into the page, or the handle on the left to drag it.

### Align text
<img width="302" alt="Schermata 2023-04-14 alle 12 06 43" src="https://user-images.githubusercontent.com/23632632/232015862-d45fa0f0-1e0e-4e4a-ae9d-dddf76853d00.png">
Using the alignment drop-down from the toolbar, you can align the whole paragraph text to the left, make it center-aligned or orient it to the right.

### Bold formatting
The **Next post** block allows you to change the "Next" default label of the link to another sentence of your choice. If so, you can apply bold formatting to the new label.

https://user-images.githubusercontent.com/23632632/232021838-2961f5aa-f27d-411c-be3f-b65ee9403a36.mov

### Italic formatting
As bold formatting, if you change the link's label, you can apply italic formatting.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/23632632/232022141-17d56d7f-fb0d-4afd-b4c2-b083db327cba.png">

### More options
Options on a block toolbar give you more features to customize the block.

- Copy block adds the Previous post block to the clipboard. Then, you can paste it anywhere you want in the block editor.
- Duplicate creates a copy of the selected block that appears after the current block.
- Insert Before inserts a new block before the selected block(s).
- Insert After inserts a new block after the selected block(s).
- Move lets you use a blue line on the editor to indicate the new position for the selected block. Use your keyboard’s up and down arrows to move the blue line. When the line is in the desired position, press Enter to move the selected block to that position.
- Copy styles copies all the block style options to the clipboard.
- Past styles after you have copied the style options to the clipboard you can go to another block and click - - - Paste styles to apply the copied styles.
- Lock allows you to prevent the block from being removed, moved, or both. In case you're trying to lock a [group block](https://wordpress.org/documentation/article/group-block/), you will see an option to also apply the same lock settings to all blocks nested inside.
- Group allows you to create a group of blocks and treat them as a unit.
- Remove Post Navigation Link deletes the selected block from the content.

## Block settings
WIP

**Comment by femkreations** [comment]
Created a new page https://wordpress.org/documentation/article/next-post-block/ and added the content. Closing this issue.
