### ISSUE TITLE
[HelpHub] Term Description

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#244]
## What is the new page you are requesting?

New article required for the Term Description block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
Page is ready: https://wordpress.org/support/article/term-description-block/

**Comment by zzap** [comment]
@femkreations awesome work :heart:  

Same few things as for Archive Title:
- At the top of article make `Note: This block only works on the archive pages.` more visible. Use `[info][/info]` for the blue notice. 
- Add in notice that this block should be used in Site editor because that's the only place you can edit archives (otherwise block won't be visible on frontend) and link to this article: https://wordpress.org/support/article/site-editor/
- Add link to [Blocks page](https://wordpress.org/support/article/blocks/) on the top of the article, like other blocks do (e.g. https://wordpress.org/support/article/paragraph-block/)

**Comment by femkreations** [comment]
@zzap Thanks for the review. I created a reusable block for the notice that we can use on all the blocks. Pls let me know if any changes are needed.

**Comment by zzap** [comment]
I modified your reusable block a bit. Contrast between link and background color wasn't high enough for accessibility. 

It looks like we don't have those notice shortcodes available at HelpHub. Regardless, we can't put any link inside. So I faked the styling but we'll have to do something sustainable about it.

Here's how it looks like now:
![reusable-archive-block](https://user-images.githubusercontent.com/1508963/158816664-96d9edd6-9cc2-4a5c-9bea-6ce32d1789cf.png)

**Comment by bph** [comment]
_Just remember:_ Reusable blocks need to be "Converted to regular blocks" before the "update" or "publish" process. Reusable blocks don't travel to the Polyglot's sites. The translators won't see the content inside the reusable block to be translated.
