### ISSUE TITLE
[HelpHub] Wolfram Cloud

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#248]
## What is the new page you are requesting?

New article required for the Wolfram Cloud block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by bph** [comment]
- [Gutenberg PR ](https://github.com/WordPress/gutenberg/pull/35656)with some screenshots and information. 
- [Core Trac Ticket](https://core.trac.wordpress.org/ticket/53326), with more information

**Comment by rmartinezduque** [comment]
Hi! I've been recently working on the article for the Wolfram embed block. Screenshots are of the current version (5.9).

Here's the [Google doc for review](https://docs.google.com/document/d/13sMdVIiSUBpTLJScDBGNe2Gdqh8-ovAPC-BLxn_RUaI/edit?usp=sharing) and the [Screenshots folder](https://drive.google.com/drive/folders/1agDArqchbNPHZYIwDVa0quQEsaCfuyn_?usp=sharing).

I use the name "Wolfram" rather than "Wolfram Cloud" due to the [recent request](https://github.com/WordPress/gutenberg/pull/39528) to change the name of the embed, but some screenshots still display the "Wolfram Cloud" name. I can replace them if you wish at a later date once the change is in production.

Please feel free to review it and let me know if any changes are needed. Thank you!

**Comment by zzap** [comment]
Hello @rmartinezduque , thank you so much for working on this :heart: 

Everything looks great and yes, we can update screenshots once the new name is mergded. 

Would you like to create this page in HelpHub? If so, I need your wordpress.org username so I can give you the access. Thanks

**Comment by rmartinezduque** [comment]
Sure, @zzap. Happy to create the page in HelpHub later this week. I'll follow the same process that you suggested in the [HelpHub Pinterest Issue](https://github.com/WordPress/Documentation-Issue-Tracker/issues/247#issuecomment-1076350037) and let you know once published. Thank you!

**Comment by rmartinezduque** [comment]
Hello! Just a quick update here that I have not forgotten this :) The Wolfram team wanted to review the article and I was waiting to see if they had any feedback before publishing it. I won't be available next week but I'm hoping to help with this once I'm back (April 18).

**Comment by rmartinezduque** [comment]
Hi @zzap,

I updated the [Google doc](https://docs.google.com/document/d/13sMdVIiSUBpTLJScDBGNe2Gdqh8-ovAPC-BLxn_RUaI/edit) with some minor changes that the Wolfram team requested. 

They also suggested this:

(1) Change the following sentence to include links to Wolfram Notebooks for more information: 

> "With the Wolfram embed block, you can embed [Wolfram Notebook](https://www.wolfram.com/featureset/notebooks/) content into your posts and pages ([deployed through the Wolfram Cloud](https://reference.wolfram.com/language/guide/CloudFunctionsAndDeployment.html))."

I don't see similar links in other HelpHub articles, so I would like you to confirm if this is possible. Thank you!

**Comment by rmartinezduque** [comment]
The HelpHub article is now published: https://wordpress.org/support/article/wolfram-embed/ as agreed. @zzap let me know when you have a chance to review the links and I'll add them to the article if necessary. Thanks again!

**Comment by zzap** [comment]
@rmartinezduque thank you so much, looks great. As for the links, the first one is OK. The second one leads to API reference which is for developers and has no value to our end users whatsoever so we'll not add it. 

Do you want to add it yourself?

**Comment by rmartinezduque** [comment]
Sure, I have just added the first link to the guide and updated the changelog. Thank you @zzap!
