### ISSUE TITLE
[HelpHub] Archive Title

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#249]
## What is the new page you are requesting?

New article required for the Archive Title block

## General

- [ ] make sure all screenshots are relevant for the current version (5.9)
- [ ] update changelog at the end of the article

**Comment by femkreations** [comment]
@zzap This page is ready for review: https://wordpress.org/support/article/archive-title-block/

**Comment by zzap** [comment]
@femkreations article looks great, thank you so much for working on it.

A few of things:
- At the top of article make `Note: This block only works on the archive pages.` more visible. Use `[info][/info]` for the blue notice. 
- Add in notice that this block should be used in Site editor because that's the only place you can edit archives (otherwise block won't be visible on frontend) and link to this article: https://wordpress.org/support/article/site-editor/
- Add link to [Blocks page](https://wordpress.org/support/article/blocks/) on the top of the article, like other blocks do (e.g. https://wordpress.org/support/article/paragraph-block/)

This list can be added as tasks to all new block issues :point_up:

**Comment by femkreations** [comment]
@zzap. Thanks for the review.  I updated with the Note, placed the blue Notice box one paragraph below as otherwise, the blue box messes up with the topics navigation (see screenshot attached)
![Screen Shot 2022-03-11 at 9 50 40 AM](https://user-images.githubusercontent.com/2823103/157923020-2fb9fc4b-024a-484e-96e5-f586d8233d29.png)
