### ISSUE TITLE
[HelpHub] Author Biography block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#267]
## New page for 6.0
- [x] Create a new article for the Author Biography block [38269](https://github.com/WordPress/gutenberg/pull/38269)
- [x] Make sure the URL slug under Permalink is: author-biography-block
- [x] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 
- [x] Convert all reusable blocks to a ‘regular block’.

## General
- [x] Make sure all screenshots are relevant for the current version (6.0)
- [x] Make sure videos are relevant for the current version (6.0)
- [x] Make sure the headings are in sentence case
- [x] Update the changelog at the end of the article

**Comment by theblogsmith** [comment]
# Post Author Biography Block
Creating a _ post author biography block_ will allow you to embed a user's **Biographical Info** from the **About Yourself** section in **Users** > **Profile** into your page or post.

In order to add a _post author biography block_, click on the inserter icon.

![Image](https://user-images.githubusercontent.com/113307503/189547412-1a3230b9-73a0-4a19-8909-de5af84824b3.gif)

You can also type /Post Author Biography and hit enter in a new paragraphy block to add one quickly

![Image](https://user-images.githubusercontent.com/113307503/189547524-ddbb07dd-7137-44de-a9f8-2d30a12d879b.png)

> Use the slash command /Post Author Biography to insert a _Post Author Biography block_

> **Resource**: detailed instructions for [adding blocks](https://wordpress.org/support/article/adding-a-new-block/).

## Block Interface
Every block comes with unique toolbar icons and block-specific user controls that allow you to manipulate the block right in the editor.

![Image](https://user-images.githubusercontent.com/113307503/189547607-08f9f752-3423-41a8-95ec-cc01990c06da.png)
> The _Post Author Biography block_ has an alignment toolbar icon.

## Alignment
When you select your _Post Author Biography block_, a toolbar will appear where you can change the block's text alignment.

![Image](https://user-images.githubusercontent.com/113307503/189547718-1cc3c64f-4b52-41f0-ab53-0b857857f541.png)

> The _Post Author Biography block_ with _Align text right_ selected.

Choose between the options to:
- **Align text left**
- **Align text center**
- **Align text right**

## More Options

![Image](https://user-images.githubusercontent.com/113307503/189547933-e74d7742-2855-47a7-ac18-314cff23bc18.png)

### Hide Block Settings

The _Hide Block Settings_ option hides (or shows) the Block Setting panel in the editor’s sidebar.

### Copy

_Copy_ can be used to copy a selected block and then you can paste it wherever you want in the editor.

### Duplicate

_Duplicate_ can be used to duplicate selected block.

### Insert Before

Insert a new block before the selected block(s).

### Insert After

Insert a new block after the selected block(s).

### Move To

If you select _Move To_, you will get a blue line inside your content, you can then use the arrows to move that line up and down to where you want the selected content to be moved into, hitting return on your keyboard at that point moves the block to that position.

### Edit as HTML

The _Edit as HTML_ option allows you to modify the HTML code of the embed block.

### Add to Reusable blocks

Using the _Add to Reusable blocks_ option lets you add the selected block to a list of reusable blocks, so you can use them on other posts or pages as well.

### Group

Select the _Group_ option if you want to create a group of blocks and treat them as a unit. You can for instance add a common background color or other blocks to the group.

### Remove Block

With the _Remove Block_ option, you can delete the selected block from your content.

## Sidebar Settings
Every block has specific options in the editor sidebar in addition to the options found in the block toolbar. _If you do not see the sidebar, simply click the ‘cog’ icon next to the Publish button._

![Image](https://user-images.githubusercontent.com/113307503/189547949-f2cd9ddf-a7cc-41a1-bfa0-77e511defa2c.png)
> The block settings can be found in the sidebar.

### Color

These options let you set custom text and background colors based on the theme, default options, or HEX codes.

![Image](https://user-images.githubusercontent.com/113307503/189548028-abbd0302-50ba-4a64-aa93-2baa39265bcb.png)
> The _Post Author Biography block_ can be customized in terms of custom text and background colors.

### Typography

These options let you set custom text sizes in terms of predetermined options (_Small_, _Medium_, _Large_, _Extra Large_) or with custom pixel (px) settings.

![Image](https://user-images.githubusercontent.com/113307503/189548140-8d9aa240-404b-4c0c-8b36-c045c9a9a449.png)
![Image](https://user-images.githubusercontent.com/113307503/189548145-d3c1faa2-41a1-432c-bff7-35edb6a6a01a.png)
> The _Post Author Biography block_ can be customized in terms of predetermined size options or custom pixel settings.

### Dimensions

These options let you set custom dimensions based on margin, padding, or both.

![Image](https://user-images.githubusercontent.com/113307503/189548268-400c9326-4bad-40ee-a93c-567ad4935e2b.png)
> The _Post Author Biography block_ can be customized in terms of margin, padding, or both.

![Image](https://user-images.githubusercontent.com/113307503/189548280-368ce88b-db39-4cea-8bf7-31f8adec8073.png)
> Click the _more options_ menu button (three stacked dots) to reset these option. 

### Advanced

The advanced tab lets you add a CSS class to your block, allowing you to write custom CSS and style the block as you see fit.

![Image](https://user-images.githubusercontent.com/113307503/189548222-6af5931c-d5a6-41ec-bc79-bb31a01a4370.png)
> The advanced section lets you add HTML anchor and a CSS class to your block.

**Comment by theblogsmith** [comment]
# Post Author Biography Block
Creating a _ post author biography block_ will allow you to embed a user's **Biographical Info** from the **About Yourself** section in **Users** > **Profile** into your page or post.

In order to add a _post author biography block_, click on the inserter icon.

![Image](https://user-images.githubusercontent.com/113307503/189547412-1a3230b9-73a0-4a19-8909-de5af84824b3.gif)

You can also type /Post Author Biography and hit enter in a new paragraphy block to add one quickly

![Image](https://user-images.githubusercontent.com/113307503/189547524-ddbb07dd-7137-44de-a9f8-2d30a12d879b.png)

> Use the slash command /Post Author Biography to insert a _Post Author Biography block_

> **Resource**: detailed instructions for [adding blocks](https://wordpress.org/support/article/adding-a-new-block/).

## Block Interface
Every block comes with unique toolbar icons and block-specific user controls that allow you to manipulate the block right in the editor.

![Image](https://user-images.githubusercontent.com/113307503/189547607-08f9f752-3423-41a8-95ec-cc01990c06da.png)
> The _Post Author Biography block_ has an alignment toolbar icon.

## Alignment
When you select your _Post Author Biography block_, a toolbar will appear where you can change the block's text alignment.

![Image](https://user-images.githubusercontent.com/113307503/189547718-1cc3c64f-4b52-41f0-ab53-0b857857f541.png)

> The _Post Author Biography block_ with _Align text right_ selected.

Choose between the options to:
- **Align text left**
- **Align text center**
- **Align text right**

## More Options

![Image](https://user-images.githubusercontent.com/113307503/189547933-e74d7742-2855-47a7-ac18-314cff23bc18.png)

### Hide Block Settings

The _Hide Block Settings_ option hides (or shows) the Block Setting panel in the editor’s sidebar.

### Copy

_Copy_ can be used to copy a selected block and then you can paste it wherever you want in the editor.

### Duplicate

_Duplicate_ can be used to duplicate selected block.

### Insert Before

Insert a new block before the selected block(s).

### Insert After

Insert a new block after the selected block(s).

### Move To

If you select _Move To_, you will get a blue line inside your content, you can then use the arrows to move that line up and down to where you want the selected content to be moved into, hitting return on your keyboard at that point moves the block to that position.

### Edit as HTML

The _Edit as HTML_ option allows you to modify the HTML code of the embed block.

### Add to Reusable blocks

Using the _Add to Reusable blocks_ option lets you add the selected block to a list of reusable blocks, so you can use them on other posts or pages as well.

### Group

Select the _Group_ option if you want to create a group of blocks and treat them as a unit. You can for instance add a common background color or other blocks to the group.

### Remove Block

With the _Remove Block_ option, you can delete the selected block from your content.

## Sidebar Settings
Every block has specific options in the editor sidebar in addition to the options found in the block toolbar. _If you do not see the sidebar, simply click the ‘cog’ icon next to the Publish button._

![Image](https://user-images.githubusercontent.com/113307503/189547949-f2cd9ddf-a7cc-41a1-bfa0-77e511defa2c.png)
> The block settings can be found in the sidebar.

### Color

These options let you set custom text and background colors based on the theme, default options, or HEX codes.

![Image](https://user-images.githubusercontent.com/113307503/189548028-abbd0302-50ba-4a64-aa93-2baa39265bcb.png)
> The _Post Author Biography block_ can be customized in terms of custom text and background colors.

### Typography

These options let you set custom text sizes in terms of predetermined options (_Small_, _Medium_, _Large_, _Extra Large_) or with custom pixel (px) settings.

![Image](https://user-images.githubusercontent.com/113307503/189548140-8d9aa240-404b-4c0c-8b36-c045c9a9a449.png)
![Image](https://user-images.githubusercontent.com/113307503/189548145-d3c1faa2-41a1-432c-bff7-35edb6a6a01a.png)
> The _Post Author Biography block_ can be customized in terms of predetermined size options or custom pixel settings.

### Dimensions

These options let you set custom dimensions based on margin, padding, or both.

![Image](https://user-images.githubusercontent.com/113307503/189548268-400c9326-4bad-40ee-a93c-567ad4935e2b.png)
> The _Post Author Biography block_ can be customized in terms of margin, padding, or both.

![Image](https://user-images.githubusercontent.com/113307503/189548280-368ce88b-db39-4cea-8bf7-31f8adec8073.png)
> Click the _more options_ menu button (three stacked dots) to reset these option. 

### Advanced

The advanced tab lets you add a CSS class to your block, allowing you to write custom CSS and style the block as you see fit.

![Image](https://user-images.githubusercontent.com/113307503/189548222-6af5931c-d5a6-41ec-bc79-bb31a01a4370.png)
> The advanced section lets you add HTML anchor and a CSS class to your block.

**Comment by theblogsmith** [comment]
A few notes for context:

- This is my first documentation contribution so I'm still figuring things out! I used this page as a template: https://wordpress.org/support/article/audio-block/
- I copied some items that were the same from this page so double-check to make sure things aren't out-of-date. 
- I changed up the language for this template item to be more specific/avoid "click here": _Detailed instructions on adding blocks can be found [here](https://wordpress.org/support/article/adding-a-new-block/)._
- I made small updates to template language throughout (like adding a dash to _block-specific_)
- I took a guess at proper heading sizes

**Comment by zzap** [comment]
Thank you so much @theblogsmith, it is great.

Heading sizes should be mostly H2 with few nested H3s.

**Comment by theblogsmith** [comment]
@femkreations @jennimckinnon - I can't mark the first checkbox so tagging you for review :) Let me know if there's anything I should keep in mind when contributing to documentation

**Comment by femkreations** [comment]
Thank you @theblogsmith for your work.The content looks great. I've created the page using this info.

https://wordpress.org/support/article/post-author-biography-block/
