### ISSUE TITLE
Upgrade PHP version on Twenty Twenty Two

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/Documentation-Issue-Tracker#352]
https://wordpress.org/support/article/twenty-twenty-two/
![image](https://user-images.githubusercontent.com/4569581/170053639-86627193-06af-4b7e-b0a2-ba403ebea03b.png)

It should say PHP v5.7

Found on Slack by Sumit Singh

**Comment by sssumitsingh** [comment]
![image](https://user-images.githubusercontent.com/23701579/170054523-f610fe2e-7e66-4019-946a-2fde2ec0f3e5.png)
We need to update here also 
![image](https://user-images.githubusercontent.com/23701579/170055150-4b524724-c0ad-48b3-8bd5-1283a825ca06.png)

**Comment by stevenlin-x** [comment]
Why is it PHP v5.7?

The official theme page says it's v5.6 or higher
https://wordpress.org/themes/twentytwentytwo/

**Comment by NekoJonez** [comment]
According to @sssumitsingh it should be v5.7 ... Maybe he can give his source.

**Comment by stevenlin-x** [comment]
1.)
> According to @sssumitsingh it should be v5.7 ... Maybe he can give his source.

> Because WP Requirements 7.4 as per this https://wordpress.org/download/ page. More information see SS.

So you got it wrong? It's not v5.7 that you're referring to, but v7.4.

2.)
As indicated above, it shouldn't be v5.7 because there is not even v5.7 to begin with as listed on the official PHP release page.
https://www.php.net/releases/

3.)
Should it be v7.4 or whatever the minimum required PHP version for the latest WordPress release is? The answer is NO.
https://wordpress.org/support/article/twenty-twenty-two/

The support article you cited is for user doc. When it comes technical requirements, the user doc simply reflects what the minimum requirement states in the official theme page on WP.org. So as long as the text string between user doc and theme page is the same, it's not user doc problem.

4.)
Should the PHP version requirement on the official theme page in the plug-in directory be fixed?
https://wordpress.org/themes/twentytwentytwo/

This is a question for the theme author, but I can try to answer it here.

The answer is NO for the following reasons:

I.) Themes have a PHP requirement separate from WP core. It's what the theme developers declares when they submit their plug-in to the plug-in directory for approval. The PHP requirement of a theme is essentially a statement from the developer: "This is the PHP version and its corresponding language features that was used when developing the theme." The same statement applies to the minimum WordPress version requirement of a theme. So you do not automatically bump up the version requirements of a plug-in when a new WP version is released; the version requirements corresponds to whatever versions were tested by the developers at the time of the plug-in release.

I'm guessing this is what tricked you. You probably thought because the name of the theme is "twentytwentytwo" (this year), then the PHP version of the plug-in must also conform to the PHP requirement of the latest WordPress release this year. That's not how it works.

II.) To think this another way, if the version requirements of a plug-in must be the same as the latest WP version, then what's purpose of citing a number in those data fields to begin? The page might as well just say "PHP Version: latest PHP version of the latest WP version". A specific data field exists to indicate the minimum version because plug-ins can have their own requirements.

III.) Another example: Twenty Ten
https://wordpress.org/themes/twentyten/

This theme is an official theme that was released 10+ years ago, still being updated this year, but its WP and PHP requirement remain at old versions.
WordPress Version: 3.0 or higher
PHP Version: 5.2.4 or higher

In the case of "Twenty Twenty-Two", despite it being a modern theme, it remained at old PHP version because themes do not typically require complex PHP language features so the theme author doesn't use the latest PHP version features unnecessarily, as it may disqualify some users.

IV.) Themes can become legacy but still being used on old versions of WP

WordPress respects backward compatibility as much as possible. Plenty users are still on old versions of WP.

If you just automatically force all themes/plug-ins conform to the latest PHP versions of a WP release, then many of these users on old WP versions, who don't need the themes/plug-ins to use the latest PHP, would be left in dust.
