### ISSUE TITLE
Improvement in the "FAQ My site was hacked" Support documentation Page

### ISSUE THREAD

**Issue by pharar** [WordPress/Documentation-Issue-Tracker#369]
Hi guys! :)
I propose to change the "Quettera" link text in the page -> "Quttera". It is a typo.

## URL of the Page with the Issue
https://wordpress.org/support/article/faq-my-site-was-hacked/

## Section of Page with the issue
https://wordpress.org/support/article/faq-my-site-was-hacked/#some-steps-to-take

I also would like to propose myself to contribute with this Page since it is directly in my area of expertise, so I'll appreciate indications how to directly work on it.

Thanks a lot!

**Comment by stevenlin-x** [comment]
Thanks for reporting.

However, instead of revise the link text, the link in question and many of the other links on the page need to be removed since they all violate the recently published external linking policy (not on the allowlist).

https://make.wordpress.org/docs/tag/external-linking-policy/
