### ISSUE TITLE
Example code probably wrong | do_action

### ISSUE THREAD

**Issue by 3ele-projects** [WordPress/Documentation-Issue-Tracker#389]
## Issue Description
In the example there is the line:
 
$value = do_action( 'example_action', $arg1, $arg2 );

If you check the function at
https://github.com/WordPress/wordpress-develop/blob/6.0/src/wp-includes/plugin.php#L441-L479

there is no return.  So it seems that no value is returned.

## URL of the Page with the Issue

https://developer.wordpress.org/reference/functions/do_action)

## Section of Page with the issue
Example usage:
Line 13

## Why is this a problem?
Developer expects different behaviour than what is shown.

## Suggested Fix
Removing the line?

**Comment by stevenlinx** [comment]
Thank you for reporting.

However, this is the scope of the Make Core team because "the example in the Description section of the page" is derived from the Docblock of the source code.

Specifically, these lines:
https://github.com/WordPress/wordpress-develop/blob/6.0/src/wp-includes/plugin.php#L413-L427

FYI, on DevHub, the Description/Parameters/Return/Hooks sections of a Code Reference page are parsed and generated from the source code after each release. 

So to see the example fixed, you'll need to file a ticket over at Core trac.
https://core.trac.wordpress.org/
