### ISSUE TITLE
Add request PR for Contributors in README

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#40]
## Issue Description

We want to keep an eye on all contributors to Docs team so we have a document [CONTRIBUTORS.md](https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/CONTRIBUTORS.md). Everyone who reported issue, fixed issue and/or participated in discussion should create PR to add their info in this document. Required info is wp.org username, GitHub username and GitHub issue number.

## URL of the Page with the Issue
https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/README.md

## Section of Page with the issue

Getting Recognition - https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/README.md#getting-recognition

## Why is this a problem?
This section is mentioning Google Docs but that's just unnecessary dispersing over more tools when we have everything we need here. Plus, having issue numbers gives more insight in which part of docs contributors were involved and therefore, provide more context.

## Suggested Fix
Replace Google docs info with GitHub PR from the description above.

**Comment by MuhammadFaizanHaidar** [comment]
@zzap  I am interested to contribute in this issue can you please assign this issue to me thanks!

**Comment by TukuToi** [comment]
If someone already has said badge/recognition I think it is not necessary?
Perhaps we should specify that as well, so we don't get "unwanted" PRs of "I am contributing XY"?

**Comment by MuhammadFaizanHaidar** [comment]
> If someone already has said badge/recognition I think it is not necessary?
> Perhaps we should specify that as well, so we don't get "unwanted" PRs of "I am contributing XY"?

I think its okay to show number of contributions one has made to the docs. Like props( 1 ), props(2) so on.
and add a field badge awarded true/false.

**Comment by zzap** [comment]
For getting the badge yes, it is not necessary but we might want to keep track off all contributions (all issues). This is probably not ideal way as it is manual and tend to grow in time (and table cell) but GitHub doesn't really track discussion participants as far as I know. Let's discuss this more.

**Comment by TukuToi** [comment]
Well, there are ways to do that, let me know if I should?
(Git API is relatively easy to use and allows for such queries automatically but we would need some server where to deploy that code)

Another possible thing is to just make a link, like so:
https://github.com/WordPress/Documentation-Issue-Tracker/issues/created_by/TukuToi
https://github.com/WordPress/Documentation-Issue-Tracker/pulls/TukuToi

Since we will be adding Git Username, this link can be created "semi dynamically"

**Comment by zzap** [comment]
Yes, that's great for people who created issues and PRs, definitely helpful. What we are missing is people who participated in discussions and fixed the issues (without PRs).

**Comment by Kenshino** [comment]
That was what I was thinking at first @zzap which is why I created that file.

But I wonder if it was potentially prohibitive to expect contributors to also know how to

1. Create branches
2. Create a PR
3. Potentially deal with branch conflicts if the file is edited across a few PRs

Hence I defaulted back to using Google Docs for the time being.

Let's consider the above before moving into anything specific
