### ISSUE TITLE
Code Reference: More Info for WP_Rewrite links

### ISSUE THREAD

**Issue by joyously** [WordPress/Documentation-Issue-Tracker#417]
## Issue Description
The More Information section for WP_Rewrite has two links to itself. It looks very similar to the Rewrite API page, but actually has more details (but missing the info about `init` hook), yet it links to the API page in the Codex.
There is also a link to a support article for Pretty Permalinks, but it doesn't link to that section of the article.

## URL of the Page with the Issue
https://developer.wordpress.org/reference/classes/wp_rewrite/

## Section of Page with the issue
More Information

## Why is this a problem?
The developer has to jump around to various pages that look alike but have slightly different information, in order to get everything needed to use the class. None of these pages indicates which parts apply only to the `post` post type.

## Suggested Fix
Unlink the two places where `WP_Rewrite` links to this page. 
Change the Rewrite API link from Codex to https://developer.wordpress.org/apis/handbook/rewrite/
Consider mentioning the `init` hook and whether any of the Properties only apply to Posts.
Add the fragment id for the Pretty Permalinks link.

**Comment by stevenlinx** [comment]
Thank you for the reporting.

I've revised the content.

1.) Regarding the self linked WP_Rewrite phrase, the source didn't link it. It's linked automatically.

2.) I also did an optional revision. I revised external link to the phrase "URL Rewriting" to linking to a Wikipedia article instead since the original external link violates external linking policy.
