### ISSUE TITLE
[HelpHub] Content review - New to WordPress - Where to Start

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#442]
## Issue Description

Content update, broken links and article structure review

## URL of the Page with the Issue

[New to WordPress - Where to start](https://wordpress.org/support/article/new-to-wordpress-where-to-start/)

## Section of Page with the issue

Full article

## Suggested Fix

- [x] Link on first paragraph [need help](https://wordpress.org/support/article/new-to-wordpress-where-to-start/#need-more-help). Is that paragraph really necessary? Suggestion: link to the Forums instead.
- [x] Change the links in the **Suggested reading includes.** section as follows:
- [x] Keep [Introduction to Blogging?](https://wordpress.org/support/article/introduction-to-blogging/)
- [x] Remove [What is WordPress](https://wordpress.org/support/article/overview-of-wordpress/)
- [x] Replace link to [WordPress Features](https://wordpress.org/support/article/wordpress-features/) with [Features](https://wordpress.org/about/features/)
- [x] Replace [Before you install WP](https://wordpress.org/support/article/before-you-install/) with [Requirements](https://wordpress.org/about/requirements/)
- [x] Step Two to Step Four - review content, remove developer jargon and links to developer articles
- [x] [Giving Back to WP](https://wordpress.org/support/article/new-to-wordpress-where-to-start/#giving-back-to-wordpress) section provides links to the Forums and Codex instead to Contribution pages. Perhaps the link should go in the previous paragraph [Need more help](https://wordpress.org/support/article/new-to-wordpress-where-to-start/#need-more-help)

**Comment by hannaw93** [comment]
I will pick this one up :)

**Comment by hannaw93** [comment]
Adjusted slightly structure: so that a section has links after the explanation, instead of vice versa. 
From mentioned tasks done:
- Link on first paragraph [need help] now leads to the form, but paragraph not removed
- Links (all) updated/replaced
- Kept [Introduction to Blogging?](https://wordpress.org/support/article/introduction-to-blogging/) since there is an issue about updating it
- Removed [What is WordPress](https://wordpress.org/support/article/overview-of-wordpress/)
-  Step Two to Step Four - reviewed content, removed developer jargon, but not links to developer articles since they so far seem environemnt related

Additionally done:
- Changed the phrase "Wordpress semantics" to "Wordpress terminology" - feel free to change back if this is a matter of sticking to the glossary, just seems for understandable for a beginner article
- Added Wodpress tutorials as an additional link to the Advanced section about learning more
- Added Wordpress lessing plans to "Giving back to Wordpress" for those who want to teach others about Wordpress

**Comment by hannaw93** [comment]
@zzap I checked if all in the checklist was addressed, this can probably go to a final review or done :)

**Comment by emmasophieyoung** [comment]
double checked links, added alt text
