### ISSUE TITLE
[HelpHub] Content revision - duplicate: WP.org vs WP.com

### ISSUE THREAD

**Issue by estelaris** [WordPress/Documentation-Issue-Tracker#473]
## Issue Description

There are two articles whose goal i to explain the difference between WP.org and WP.com

## URL of the Page with the Issue

[WordPress.org and WordPress.com](https://wordpress.org/support/article/wordpress-org-and-wordpress-com/)
[WordPress vs WordPress.com](https://wordpress.org/support/article/wordpress-vs-wordpress-com/)

## Why is this a problem?

Different approach to resolve the same question, yet the information is duplicated

## Suggested Fix

The second article WP vs WP.com seems to address the question better. I suggest to delete the first article.

**Comment by NewYorkerLaura** [comment]
@zzap I can work on the merger of these two articles today at WordCamp Asia. My .org name is NewYorkerLaura

**Comment by NewYorkerLaura** [comment]
@zzap My suggested merging of the text is below. I took information from both articles.

[WordPress vs. WordPress.com](https://wordpress.org/documentation/article/difference-between-wordpress-org-and-wordpress-com/#wordpress-vs-wordpress-com)
People are often confused about the differences between [WordPress.org](https://wordpress.org/) and [WordPress.com](https://wordpress.com/). The same core WordPress software is deployed in two very different ways through WordPress.com and WordPress.org.
What is WordPress.org?
WordPress is the free, Open Source web publishing software project, owned by no one individual or company. WordPress.org is the official website for self-hosted WordPress installations.  “WordPress.org” or “self-hosted WordPress” for disambiguation purposes), is software that you can download and install on any web host. It began in 2003 as a fork of b2/cafelog. Licensed by the GPL, you are free to use WordPress without restriction. 
Self-hosting means that you have downloaded a copy of the WordPress software and installed it on a server, which is a computer with special software that lets you serve websites and other data to users through the internet. This server could be an old PC in your basement (which is not really recommended) or in a high-tech data center. It’s up to you. A self-hosted installation of WordPress enables you to create a website that you fully own and control, and you are completely responsible for configuring and maintaining the WordPress installation.
What is WordPress.com?
WordPress.com (a.k.a. “wpcom” or “WP.com”)  is both a website and a business run by a company called [Automattic](https://automattic.com/). WordPress.com launched in 2005, and is the largest WordPress install in the world. It is powered by WordPress.
You can create a free account on WordPress.com to have access to a hosted version of WordPress on which you can create a website. With this hosted version, the hosting company (in this case Automattic) takes responsibility for maintaining the server and WordPress installation, relieving you of that burden so you can solely create useful content.
Because WordPress.com has to support many different sizes and types of sites, they provide a limited number of options when it comes to customizing individual sites. There are only a fixed number of themes (site templates) that determine the look-and-feel of their sites, as well as a small number of plugins(software modules) that provide different types of functionality.
WordPress.com makes money by charging for feature upgrades. For example, if you want to use your own domain name on a WordPress.com site, there is a small fee to do so. WordPress.com has blogs from people who are just starting to blog to large enterprise organizations. There are also many companies that pay WordPress.com to host very large WordPress installations, such as BBC America, The New Yorker Magazine, and the official Star Wars Blog.
[Overlap](https://wordpress.org/documentation/article/difference-between-wordpress-org-and-wordpress-com/#overlap) between WordPress and WordPress.com
What is the overlap between WordPress and WordPress.com?
Matt Mullenweg is both the co-founder of WordPress.org project and the CEO of Automattic ( the company that owns WordPress.com). 
Matt is involved with both WordPress and WordPress.com. Some WordPress contributors are also employees of Automattic, but as WordPress is an Open Source Project, anyone can contribute. Being an employee of Automattic is not a requirement. There are many WordPress contributors, most of which have no connection with WordPress.com.
Development decisions about WordPress are made without specific regard to their impact on WordPress.com. Any special changes that WordPress.com needs are made on that side, by Automattic employees.
[Additional resource](https://wordpress.org/documentation/article/difference-between-wordpress-org-and-wordpress-com/#additional-resource)
This video is an overview of the differences between WordPress and WordPress.com:
See more here: https://learn.wordpress.org/workshop/what-is-the-difference-between-wordpress-org-and-com/
[FAQ](https://wordpress.org/documentation/article/difference-between-wordpress-org-and-wordpress-com/#faq)
Why can’t I call WordPress.com just “WordPress”?
Because it isn’t clear what you’re talking about — the Open Source project, or the hosted service. They are distinct, and statements about one aren’t necessarily true about the other. WordPress.com is its name. You wouldn’t call bit.ly, the popular link shortening service, just “bit,” would you?
Can I migrate my WordPress.com site to self-hosted WordPress?
Absolutely! Users can migrate their WordPress.com blog to a self-hosted WordPress install. 
Automattic’s relationship to WordPress?
Automattic uses WordPress to power WordPress.com, and it contributes back code and time to the WordPress project. It is a symbiotic relationship. It isn’t accurate to say that WordPress is Automattic’s product, or that WordPress came from Automattic. Indeed, the opposite is true — Automattic came from WordPress, and Automattic (through WordPress.com) exists as part of the vast WordPress community and ecosystem.
Why doesn’t Automattic rename WordPress.com to something more distinct?
You would have to ask them. Likely, the downsides of a rebranding campaign would outweigh the benefits.
