### ISSUE TITLE
[HelpHub] Twenty Fifteen: Add gradient background options that fit the theme color scheme

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#499]
Trac ticket: https://core.trac.wordpress.org/ticket/49760

Article: https://wordpress.org/support/article/twenty-fifteen/

**Comment by samxmunoz** [comment]
Taking this one.

**Comment by samxmunoz** [comment]
@femkreations - reviewing the Trac ticket, I'm thinking under the "What else can you do?" we add the following:

You can also select a gradient option for certain blocks that fit the theme color scheme:

![Image](https://user-images.githubusercontent.com/43501707/208979102-b9bc9bb3-bc66-490e-9052-0eb60f0ff985.png)

**Another place this could go is under the "Choose a Featured Color Scheme" selection - but I didn't want that to be confusing since this feature isn't available under the "Customizer" but rather for specific blocks.**

I've updated the doc & placed it in "Updated" status for release January 11th

**Comment by femkreations** [comment]
Added the info to the page Thanks @samxmunoz.
https://wordpress.org/documentation/article/twenty-fifteen/#what-else-can-you-do
