### ISSUE TITLE
[HelpHub] Tag Cloud block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#701]
Article:  https://wordpress.org/documentation/article/tag-cloud-block/

## Update for 6.2
- [x] Add typography supports. [43452](https://github.com/WordPress/gutenberg/pull/43452)

## General
- [x] Make sure all screenshots are relevant to the latest version 
- [x] Make sure videos, if any, are up to date 
- [x] Add ALT tags for the images
- [x] Make sure the headings are in sentence case
- [x] Convert all reusable blocks to a ‘regular block’.
- [x] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by carolinan** [comment]
- Scheduled the update for April 30, 2023 9:19 am UTC+0
- Added screenshots of the new tabbed settings sidebar
- Added information about Typography options and linked to the overview article

**Comment by peeranat-dan** [comment]
## Guideline reviews

How to add a Tag Cloud block to your post or page:

This should be `h2` not just bold text. According to [this guideline](https://make.wordpress.org/docs/style-guide/general-guidelines/document-structure/). Also, ":" should be removed.

---

[Block Toolbar](https://wordpress.org/documentation/article/tag-cloud-block/#block-toolbar)

This one should be titled as **Block toolbar**. According to this [Capitalization in titles and headings](https://make.wordpress.org/docs/style-guide/language-grammar/capitalization/#capitalization-in-titles-and-headings).

Each options under Block toolbar should be `h3`.

- Transform to (In the article has :, please remove)
- Drag icon
- Move handles
- Change alignment  
- More options

---

[Block Settings](https://wordpress.org/documentation/article/tag-cloud-block/#block-settings)

This one should be titled as **Block settings**. According to this [Capitalization in titles and headings](https://make.wordpress.org/docs/style-guide/language-grammar/capitalization/#capitalization-in-titles-and-headings).

---

[Settings tab](https://wordpress.org/documentation/article/tag-cloud-block/#settings-tab)

For the "Smallest size/ Largest size" heading, ":" should be removed and the content should break into another line in order to contains consistency between the topics.

Also, all headings inside this topic should be changed into `h4` instead of bold text. Since the [Styles tab](https://wordpress.org/documentation/article/tag-cloud-block/#styles-tab) has been using that pattern and it looks amazing.

**Comment by peeranat-dan** [comment]
## Content Review

/Tag now come with these select options.
<img width="285" alt="image" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/85337926/795131a4-8f43-48f4-a162-7c391dbd87eb">

---

[Settings tab](https://wordpress.org/documentation/article/tag-cloud-block/#settings-tab)

<img width="267" alt="image" src="https://github.com/WordPress/Documentation-Issue-Tracker/assets/85337926/8ec7ebbe-9050-4ef3-bccb-d78bf52e7a14">

Now there are 3 taxonomy types. So maybe the content should be changed into:

Select from the following three [taxonomy](https://wordpress.org/documentation/article/taxonomies/) types: Categories, Tags, or Pattern Categories. The Tag Cloud is displayed based on the selected taxonomy.

---

**Comment by peeranat-dan** [comment]
@Leonardus-Nugraha ready for review

**Comment by Leonardus-Nugraha** [comment]
Thank you @peeranat-dan! I've reviewed the updates and made changes to the article accordingly.

Great job!
