### ISSUE TITLE
Check for WP_Block_Patterns_Registry class before registering a block pattern

### ISSUE THREAD

**Issue by mburridge** [WordPress/Documentation-Issue-Tracker#75]
## Issue Description
The page on registering block patterns and block pattern categories doesn't mention a check for `if ( class_exists( 'WP_Block_Patterns_Registry' ) )`. Should it?

## URL of the Page with the Issue
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/

## Section of Page with the issue
Prior to https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#register_block_pattern

## Why is this a problem?
Older versions of WordPress won't have the `WP_Block_Patterns_Registry` class as block pattern functionality doesn't exist in older versions of WordPress or earlier versions of Gutenberg.

## Suggested Fix
Before registering a block pattern using `register_block_pattern()` or a block pattern category using `register_block_pattern_category()` it's advisable to check for the existence of the `WP_Block_Patterns_Registry` class in order to ensure that the site supports block patterns. This can be done by wrapping the registration code inside of a conditional check thus `if ( class_exists( 'WP_Block_Patterns_Registry' ) ) {...}`

```
function myplugin_register_patterns() {

  if ( class_exists( 'WP_Block_Patterns_Registry' ) ) {

    register_block_pattern_category(
     ...
    );

    register_block_pattern(
     ...
    );

  } 
  
}
 
add_action( 'init', 'myplugin_register_patterns' );
```

**Comment by stevenlin-x** [comment]
1.)
This ticket needs to be closed here since it's not the scope of this repo.

Editing content in Block Editor Handbook is the scope of the gutenberg repo:
https://github.com/WordPress/gutenberg/tree/trunk/docs

On the "[Patterns](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/)" page, if you click the GitHub "Edit" button next to the title, it will lead you to the following file of the gutenberg repo, which is where you propose the changes
https://github.com/WordPress/gutenberg/edit/trunk/docs/reference-guides/block-api/block-patterns.md

2.)
From the Coverage section of README.md for this "Documentation-Issue-Tracker" repo:
https://github.com/WordPress/Documentation-Issue-Tracker#coverage
"The Documentation Team's handbook
...
All other Make / WordPress team handbooks are maintained by internally by said respective teams. Please contact them on Make / WordPress Slack to suggest changes."

**Comment by mburridge** [comment]
Thanks @stevenlin-x. I've created [PR #42117](https://github.com/WordPress/gutenberg/pull/42117) in the Gutenberg repo to address this issue. Closing.
