### ISSUE TITLE
[HelpHub] Feedback on Additional guide to using the Site Editor

### ISSUE THREAD

**Issue by zzap** [WordPress/Documentation-Issue-Tracker#760]
## Issue Description
Originally reported by https://profiles.wordpress.org/djcuppat/

> Any mention of Custom CSS being absent would be appreciated, especially as there are many limitations to the new block-based system for styling that would help a developer decide whether to create a child theme or not, before they journey down the rabbit-hole!
> 
> For example, even something as simple as modifying link text appearance site-wide or individually is missing essential ingredients, such as status css changes (hover, visited, etc.) and text-decoration rules
> 
> Thanks for listenin’

## URL of the Page with the Issue

https://wordpress.org/documentation/article/additional-guide-to-using-the-site-editor/

**Comment by zzap** [comment]
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by atachibana** [comment]
I'd like to add the following question and ansert at the bottom.
I would also replace "Appearance > Editor (beta)" with "Appearance > Editor" in this page, since the site editor is no longer beta.

## How to customize your site design at a global level

Since WordPress 5.9, you can set the colors, typography, layout, spacing, and more, for the entire site via Styles.
You can also edit the default appearance of blocks to streamline the look and feel of your site.
Fore more details, refer [Styles Overview](https://wordpress.org/documentation/article/styles-overview/).
