### ISSUE TITLE
Using Permalinks: Update Caddy references 

### ISSUE THREAD

**Issue by basilhendroff** [WordPress/Documentation-Issue-Tracker#8]
### Source article
[Using Permalinks](https://wordpress.org/support/article/using-permalinks/)

### The problem I'm having
The WordPress article [Using Permalinks](https://wordpress.org/support/article/using-permalinks/) has the one and only reference in WordPress support docs to Caddy. However, the reference is for Caddy V1, which is now defunct. Caddy V2 has been out since May 2020.
### Suggested improvements

1. Under the section [mod_rewrite: “Pretty Permalinks”](https://wordpress.org/support/article/using-permalinks/#mod_rewrite-pretty-permalinks), alter the bullet point...
>* Caddy using rewrite, e.g. according to this [tutorial](https://denbeke.be/blog/servers/caddy-server-and-wordpress-php-fpm/)

...to instead read...

>* [Caddy](https://caddyserver.com/) automatically in a default WordPress installation. This is the default built-in behaviour of the `php_fastcgi` directive.

2. Under the section [Using “Pretty” permalinks](https://wordpress.org/support/article/using-permalinks/#using-pretty-permalinks), add the following bullet point:
> * For [Caddy](https://caddyserver.com/), a web server that supports HTTPS natively, the rewrite rule may need to be adjusted if WordPress files are moved to a subdirectory. Refer to [Using Caddy to give WordPress its own directory](https://caddy.community/t/using-caddy-to-give-wordpress-its-own-directory/13185) for details.

The suggested text improvements were discussed in this Caddy forum thread [WordPress: Using Permalinks](https://caddy.community/t/wordpress-using-permalinks/13351) 
### References
1. [Using Permalinks](https://wordpress.org/support/article/using-permalinks/)
2. [WordPress: Using Permalinks](https://caddy.community/t/wordpress-using-permalinks/13351)

**Comment by zzap** [comment]
Same as #14, #22 and #23 

Hello @basilhendroff ,

Thank you very much for your proposal. 

As this is end user documentation we don't want to overwhelm users with every single software they can come across with. This article is covering the most common cases they will most likely use. I'm in business for over a decade and only now heard about Caddy. 

I suggest writing a blog post/tutorial and submitting link to review for possible `See Also` resource. 

Thank you

**Comment by basilhendroff** [comment]
Hi @zzap,

> I suggest writing a blog post/tutorial and submitting link to review for possible `See Also` resource.

I would be pleased to do this for the issue, however, I have adopted exactly this approach with issue #6 and it also was rejected. There does not appear to be a consistent methodology between doc maintainers.

Can I also suggest that issues are not closed initially, but feedback provided to contributors? This will allow contributors a chance to respond to the feedback.  This will save the contributor from having to open the issue a second time.

**Comment by atachibana** [comment]
@basilhendroff 

Hi, my English must be bad... But, #6 enhanced your suggestion and added See Also. Please check at the bottom of https://wordpress.org/support/article/giving-wordpress-its-own-directory/

**Comment by basilhendroff** [comment]
> Hi, my English must be bad... But, #6 enhanced your suggestion and added See Also. Please check at the bottom of https://wordpress.org/support/article/giving-wordpress-its-own-directory/

Ah, Akira-san. Gomenasai. Wakarimasen.

I did interpret your response as _'A `See Also` section would be considered if a similar request was received for another webserver'_. My apologies.

As I've suggested to @zzap, it would probably be a good idea not to close issues immediately. but to have the contributor involved in the feedback loop. This way, the contributor can say _'Yeah. I've checked the changes. Looks good. You can go ahead and close the issue'_, or provide additional feedback. Alternatively, leave it to the contributor to close the issue they opened.

The whole idea of leaving issues open on GitHub and encouraging a dialogue (commenting) is that it allows the contributor and doc maintainer to interate to something that would be acceptable to both parties. Allowing the contributor to close the issue gives them a chance to 'sign-off' on the change. Here's an example of an issue that was opened and closed by the contributor after a dialogue had taken place [Can't load/save the settings file](https://github.com/basilhendroff/truenas-iocage-rslsync/issues/1).

**Comment by francislavoie** [comment]
> As this is end user documentation we don't want to overwhelm users with every single software they can come across with. This article is covering the most common cases they will most likely use. I'm in business for over a decade and only now heard about Caddy.

@zzap I'd strongly suggest you reconsider. Caddy is the easiest way to serve a WordPress site securely, with TLS. Most WordPress sites only need 4 lines of config:

```
example.com

root * /var/www/wordpress
php_fastcgi unix//run/php/php-8.0-fpm.sock
file_server
```

Caddy will automatically fetch a certificate from Let's Encrypt or ZeroSSL when it starts up, making it unnecessary to run certbot or other tools to do it. https://caddyserver.com/docs/automatic-https

Caddy is written in Go, so it's a single static binary, it can run on anything. Also, being written in Go means it's immune to memory safety vulnerabilities, which Apache and Nginx are vulnerable to, such as Heartbleed, because they're written in C. https://www.abetterinternet.org/docs/memory-safety/ 

Closing issues like this and leaving Caddy overlooked is the reason more people haven't heard of it. I urge you to give it a try, and understand its advantages, before making the decision to hinder its adoption by the broader WordPress community.

**Comment by basilhendroff** [comment]
@zzap Some chronological events to consider when reviewing @francislavoie's comments.

1. If [this infographic](https://hostingtribunal.com/blog/wordpress-statistics/) is to be believed, around 75% of hacked CMS sites in 2021 were built on WordPress. 
2. Apache has the largest webserver market share. This is not surprising given [it was released in 1995](https://en.wikipedia.org/wiki/Apache_HTTP_Server). Apache code is not end-user friendly. The difficulty for the average WordPress user in using Apache code properly could be contributing to the large number of hacked WordPress sites.
3. NginX has the second-largest share of the webserver market. Again, this is not surprising given [it was released in 2004](https://en.wikipedia.org/wiki/Nginx). NginX code is easier to comprehend than Apache code, but hasn't necessarily made it any easier to take advantage of newer internet security trends established over the last five years or so.
4. Caddy V2 was released in 2020. It's a modern webserver with automatic TLS making it the easiest way to turn a http:// website into a https:// website. Caddy code is much easier for the average user to get their head around. It reads almost like prose.
5. Until April 2016, certificates were expensive for TLS encryption and generally out-of-bounds for the average WordPress user. From April 2016, [Let's Encrypt](https://en.wikipedia.org/wiki/Let%27s_Encrypt) supplied certificates free of charge. The downside was a short lifetime (by design) of three months for the certificates. Caddy automatically renews certificates making the renewal process completely transparent to the end-user.
6. In October 2017, [Google Chrome started warning users](https://www.august.com.au/news/google-chromes-not-secure-warning-for-http-sites/)s if an accessed site was not secure i.e. using http://. Setting up a secure website is probably out-of-scope for the average user who uses Apache or NginX. It's completely automatic and transparent for the Caddy user.

References:
1. [Global Web Server Market Share September 2021](https://hostadvice.com/marketshare/server/)
2. [35+ WordPress Statistics for the Budding Webmaster [Infographic]](https://hostingtribunal.com/blog/wordpress-statistics/)
3. [Let's Encrypt](https://letsencrypt.org/)
4. [Let's Encrypt - Wikipedia](https://en.wikipedia.org/wiki/Let%27s_Encrypt)
5. [Apache - Wikipedia](https://en.wikipedia.org/wiki/Apache_HTTP_Server)
6. [NginX - Wikipedia](https://en.wikipedia.org/wiki/Nginx)
7. [Caddy - Wikipedia](https://en.wikipedia.org/wiki/Caddy_(web_server))
8. [Google Chrome’s ‘Not Secure’ warning for HTTP sites](https://www.august.com.au/news/google-chromes-not-secure-warning-for-http-sites/)

**Comment by francislavoie** [comment]
> Caddy V2 was released in 2020.

I also want to point out that Caddy has been around since 2015, it's not a new project by any means. Caddy v2 was a rewrite started in summer of 2019, and released in early 2020 to solve some fundamental mistakes in the design (because there was a lack of cohesive configuration design in the early versions).

Caddy is _most definitely_ a production ready server, large companies use it to serve tens of thousands of domains or more.

**Comment by basilhendroff** [comment]
@zzap Please consider adding the following link for a `See Also` resource:

[Caddy considerations when using permalinks in WordPress](https://caddy.community/t/caddy-considerations-when-using-permalinks-in-wordpress/13583)

Also, under the section [mod_rewrite: “Pretty Permalinks”](https://wordpress.org/support/article/using-permalinks/#mod_rewrite-pretty-permalinks), please remove the now obsolete Caddy V1 bullet point: 
>* Caddy using rewrite, e.g. according to this [tutorial](https://denbeke.be/blog/servers/caddy-server-and-wordpress-php-fpm/)

**Comment by zzap** [comment]
Hello all,

I admire your passion for this topic and have no doubt that Caddy is everything you say it is. However, this is not a matter of convincing me or anyone in Documentation team that Caddy is good. 

WordPress [officially recommends](https://wordpress.org/about/requirements/) Apache and NginX. According to [W3 Techs](https://w3techs.com/technologies/overview/web_server) those are by far the most used servers. Microsoft server is in our documentation since the Codex time and once we start reviewing end user docs for external links, we'll review just how relevant that info is today.

We are not removing anything from existing documentation lightly but we are also not adding anything lightly. The truth is Caddy is on 8th (last) place together with 7 other servers. With 0.1% share, and not being officially recommended by WordPress, it's not really candidate for adding it into official documentation. 

Just the same as you'll find setting WordPress and WordPress.org environments instructions in core, meta and other handbooks covering Linux distributions very much in general, and usually only Ubuntu. It's just overwhelming and not helpful for end user to cover every possibility.  

As we already stated, this info will be reviewed for adding in `See Also` section but it's just not relevant enough for adding it into article itself. Thank you.

**Comment by zzap** [comment]
I'm adding `external links` label and reopening issue so that we can discuss relevance for external resource.

**Comment by dimkasta** [comment]
@zzap I would also like to ask you to reconsider.

Answering to your previous posts, with all due respect, I cannot understand the resistance to fix the obsolete info about Caddy in the documentation

It's not a matter of Caddy being recommended by Wordpress or not. Caddy is already referenced in the documentation. It's not new extra software, as you say, that would overwhelm users.

Users ARE currently being overwhelmed though by those obsolete references because they are led to use problematic configurations.

**Comment by xpufx** [comment]
At the very least put a note that says the url you guys are pointing to pertains to caddy v1.

**Comment by atachibana** [comment]
@dimkasta 

Under an effort to remove technical sections from user documentation (#30), links containing Caddy V1 information and other software have been removed from this page.
https://wordpress.org/support/article/using-permalinks/

Those technical parts are stored in google docs and will be pasted somewhere in the future after external link consideration (#70).
