### ISSUE TITLE
Wrong Version Dates on https://codex.wordpress.org/WordPress_Versions

### ISSUE THREAD

**Issue by mutlusun** [WordPress/Documentation-Issue-Tracker#880]
## Issue Description
The webpage https://codex.wordpress.org/WordPress_Versions list all wordpress versions and their corresponding release date. Unfortunately, multiple entries seem to be incorrect:

- After 6.1.2 follows 6.2.2 but has the correct link to 6.1.3 (In this line also a comma between month day and year is missing). In addition the year of release is wrong.
- 6.2.1 and 6.2.3 seem to be released in 2022 even though 6.2 was released in 2023.
- In the last line (6.2.2) a comma between the month day and year is missing.

## URL of the Page with the Issue

https://codex.wordpress.org/WordPress_Versions

## Section of Page with the issue

Version table.

## Why is this a problem?

This looks a bit like nitpicking but we use the information from this table for further automated processing of wordpress pages. Thus it is important for us to have correct dates on this page.

## Suggested Fix

Correct the release dates.

Thank you for your help and all your work!

I wasn't sure if this was the right bug tracker, but I didn't know where else to report it.

**Comment by estelaris** [comment]
The link to the wrong 6.2.2. has been removed because there was no 6.1.3. version released.

**Comment by stevenlinx** [comment]
This Issue is not fully fixed.

1.)
@estelaris:
> The link to the wrong 6.2.2. has been removed because there was no 6.1.3. version released.

As I'm checking at this moment, the link to the text "6.2.2" still exists and links to "version-6-1-3" on HelpHub, unless you mean the content of the link has been removed, which now shows 404 status (i.e. it won't mislead the user to the wrong page).

The table row in question should have been removed instead because there is another of the same "6.2.2" table row further down that links to the correct page.

2.)
@mutlusun

You've errors in your description.

> After 6.1.2 follows 6.2.2 but has the correct link to 6.1.3 ...

There seems to be a typo here. The word "correct" should be "incorrect".

> 6.2.1 and 6.2.3 seem to be released ...

By "6.2.3", I assume you mean "6.2.2" since there are no "6.2.3" mentioned anywhere on the page.


3.)
Here is a list of things that should have been fixed:

I.) The "6.2.2" table row in the "6.1" area shall be removed because there is another of the same "6.2.2" table row further down that links to the correct page.

II.) The table rows "6.2.1" and "6.2.2" should have the year 2023.

III.) The table row "6.2.2" should have a comma in the date.

IV.) The table row "6.1.2" has the wrong Blog link (it links to "6.2.1"). It should be unlinked since there are no corresponding "6.1.2" blog post.

V.) The Changelog post for "6.1.2" incorrectly mentions "6.2.1" in its content body, which should be changed to "6.1.2".
https://wordpress.org/documentation/wordpress-version/version-6-1-2/


If the above list is correct and nothing more to add, then I'll follow through with the revisions needed.

**Comment by ankitpanchal75** [comment]
Thanks for finding the issues @stevenlinx, A few data is not correct on the page.

**Comment by estelaris** [comment]
@stevenlinx before you start fixing, here is a meta ticket talking about the same issue. There seems to be a full misunderstanding on what happened.

Summary:

**6.1 - released on** [Nov 2022](https://wordpress.org/news/2022/11/misha/)
- Correct date on [Download releases page](https://wordpress.org/download/releases/)
- Correct date on [HH versions list page](https://wordpress.org/documentation/article/wordpress-versions/)
- Correct date on [HelpHub](https://wordpress.org/documentation/wordpress-version/version-6-1/)
- Correct date on [Codex](https://codex.wordpress.org/WordPress_Versions)

**6.1.1 released on** [15 November 2022](https://wordpress.org/news/2022/11/wordpress-6-1-1-maintenance-release/)
- Correct date on [Download releases page](https://wordpress.org/download/releases/)
- Correct date on [HH versions list page](https://wordpress.org/documentation/article/wordpress-versions/)
- Correct date on [HelpHub](https://wordpress.org/documentation/wordpress-version/version-6-1-1/)
- Correct date on [Codex](https://codex.wordpress.org/WordPress_Versions)

**6.1.2 released on 16 May 2023** ([there is no release announcement](https://wordpress.org/news/category/releases/))
- Correct date on [Download releases page](https://wordpress.org/download/release
- Does not exist on [HH versions list page](https://wordpress.org/documentation/article/wordpress-versions/)
- Correct date on [HelpHub](https://wordpress.org/documentation/wordpress-version/version-6-1-2/)
- Correct date on [Codex](https://codex.wordpress.org/WordPress_Versions)
- Codex version number correctly links to [HH version page](https://wordpress.org/documentation/wordpress-version/version-6-1-2/)
- Codex blog on [6.1.2 links to 6.2.1 ](https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/)

**6.1.3 released on 20 May 2023** ([there is no release announcement](https://wordpress.org/news/category/releases/))
- Same date on [Download releases page](https://wordpress.org/download/release
- Does not exist on [HH versions list page](https://wordpress.org/documentation/article/wordpress-versions/)
- Same date on but page does NOT exist [HelpHub](https://wordpress.org/documentation/wordpress-version/version-6-1-3/)
- Same date on [Codex](https://codex.wordpress.org/WordPress_Versions)
- Codex version number is incorrect **shows as 6.2.2** and [is a 404](https://wordpress.org/documentation/wordpress-version/version-6-1-3/)
- Codex blog on [6.1.3 links to 6.2.2 ](https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/)

**6.2 released on [March 29, 2023](https://wordpress.org/news/2023/03/dolphy/)**
- Correct date on [Download releases page](https://wordpress.org/download/releases/)
- Correct date on [HH versions list page](https://wordpress.org/documentation/article/wordpress-versions/)
- Correct date on [HelpHub](https://wordpress.org/documentation/wordpress-version/version-6-2/)
- Correct date on [Codex](https://codex.wordpress.org/WordPress_Versions)

Versions 6.2.1 and 6.2.2 are all correct. The problems are with **6.1.2 and 6.1.3**

**Comment by stevenlinx** [comment]
1.)
@estelaris, thank you for the clarification; your list was detailed.

I've added your suggestion to the list of revisions: the first "6.2.2" table row should be "6.1.3".

revisions:
* instead of removing the first "6.2.2" table row, change it to "6.1.3"

on the same "6.1.3" table row:
* unlink the HelpHub version page (does not exist)
* fix date: added comma to the date and revise year to 2023
* unlink the Changelog link
* unlink the Blog link

2.)
I've made the rest of the revisions ( II. ~ V. ) as according to the list that I posted above, which includes the change for 6.1.2.

Note: The format for 6.1.2 uses the new template and it seems you can't specify no blog link, so I used "https://no-blog".

**Comment by mutlusun** [comment]
Thank you all for your work! Sorry for not responding earlier, I haven busy with work this week.

For me, all issues with the table are solved. So I will close it. If you see other problems please reopen.

**Comment by estelaris** [comment]
Asked in dev chat a clarification regarding the missing release announcements.

**Comment by estelaris** [comment]
Per @peterwilsoncc's response after dev chat, we can close the ticket, as the lack of blogs and announcements was probably an oversight and removing the links, as mentioned by @stevenlinx is the best course of action.

 "Updates are usually posted to [w.org/news](http://w.org/news) for security releases but I can see that they were for the 6.1 versions. Maybe an oversight or maybe they were incorrectly tagged."
 Have caught up on the info:
[wordpress.org/news](http://wordpress.org/news) posts are published for the highest version only but mentions the security fixes have been backported
[wordpress.org/support/wordpress-version/*](http://wordpress.org/support/wordpress-version/*) posts ought to be created for each of the backported versions too. if they haven't been created then likely an oversight
https://codex.wordpress.org/WordPress_Versions ought to be updated with the old versions
[Link to Slack conversation](https://wordpress.slack.com/archives/C02RQBWTW/p1688591064070909)
