### ISSUE TITLE
Site Editor Support Doc 

### ISSUE THREAD

**Issue by annezazu** [WordPress/Documentation-Issue-Tracker#93]
Similar to https://wordpress.org/support/article/wordpress-editor/ and https://wordpress.org/support/article/template-editor/, need to create a Site Editor support doc for now.

In the future, I can imagine there can be a consolidated version when the experiences are more streamlined. For now, it seems wise to have a separate Site Editor doc that links out to things like the block theme doc, Styles doc, etc.

**Comment by annezazu** [comment]
Starting an empty doc here https://wordpress.org/support/wp-admin/post.php?post=15201243&action=edit so I can reference https://wordpress.org/support/article/site-editor/ in this issue: https://github.com/WordPress/gutenberg/issues/21245

**Comment by carolinan** [comment]
There is more than one way to add a static homepage, which is part of the difficulty.

Themes have two templates that affect the homepage: home, and front-page. But this has never been relevant for end users, because if the theme is built correctly, their settings just work.

From the theme developer handbook:
**front-page.php**
The front page template is always used as the site front page if it exists, regardless of what settings on Admin > Settings > Reading.

**home.php**
The home page template is the front page by default. If you do not set WordPress to use a static front page, this template is used to show latest posts.

Theme developers that use front-page.php normally use PHP to add conditional if/else statement to display different content depending on the setting: And this is not possible with the HTML templates.

If the theme does not include a home.html template, the user can create a front-page template in the site editor (templates > Add new > Front page)
This front-page template does **not** respect the reading settings, **it always display the blocks that you add to it.**
The user can not choose to create a home template.

Thirdly, if the theme does not include a home.html template, the user can edit the content of the home page by adding blocks to the index template without assigning a page as the static home page.
They were not able to do that without code in classic themes.

**Comment by carolinan** [comment]
Here is a new draft text for the home page:


<h2 id="how-to-update-what-your-homepage-displays">How to update what your homepage displays</h2>



<p>Your homepage can show a list of your latest blog posts or a static page with custom content.</p>



<p>Which setting you use depends on the templates that are included in your theme. To view the list of templates, go to the Administration Screen > Appearance > Editor (beta) > Templates.</p>



<p>If your theme does not have a Home or Front page template, select the Add New button and create a new Front Page.</p>



<p>If your theme has a Front Page template, click on the template name to open the editor.</p>



<p>If your theme has a Home template, you can edit the template or set what you want to appear in the Administration Screen > Settings > Reading.<br>To learn how to select a static page for your homepage, please see the support article <a href="https://wordpress.org/support/article/creating-a-static-front-page/" data-type="URL" data-id="https://wordpress.org/support/article/creating-a-static-front-page/">Creating a Static Front Page</a>.</p>



<h3 id="how-to-customize-your-homepage">How to customize your homepage</h3>



<p>To customize your homepage, go to the Administration Screen > Appearance > Editor (beta). The editor will open to your homepage, and you can start editing.</p>



<p><strong>Latest Blog Posts</strong></p>



<p>Block themes display lists of blog posts with the Query Loop block and the Post Template block.<br>The <a href="https://wordpress.org/support/article/query-loop-block/" data-type="URL" data-id="https://wordpress.org/support/article/query-loop-block/">support article for the Query Loop Block</a> explains how to configure the block.<br><br>When you add a block inside the post template block, it is repeated for every post in the list. The Post Title and Post Featured Image, Post Author, Post Date, Post Category, and Post tags are examples of blocks that you can use to customize your blog.</p>



<p id="static-page"><strong>Static page</strong></p>



<p>If you have selected a static page for your home page, and you want it to have a different design than other pages, you need to assign it a template.</p>



<p>First, open the page in the editor.<br>Next, open the page settings sidebar and select or create a new template in the Template section.</p>

**Comment by annezazu** [comment]
Thanks SO much @carolinan. This is very helpful and has been integrated. My only concern is how to address what happens when you have the option to create a new Front page template which then isn't able to be selected from the Template list when editing a page you've set as your homepage. This might be fairly edge case though so am going to move on for now, unless you think otherwise. I agree this is pretty complex! For now, I've added this under "Static Page" to try to cover it:

>Please note that if you add a Front Page template in the Site Editor, it will always be used as the front page regardless of what setting you choose under Admin > Settings > Reading. You will need to either customize that template to your liking or remove it to then adjust the homepage settings again. 

Otherwise, the following has been done:
- Added in Styles, Templates, and Template part sections with links to support docs. 
- Added in a section on site icon since that actually got backported!
- Added a section on how to return to your dashboard since I imagine this will come up. 
- Finished the section on "How to browse between templates and template parts" including a very short video.

What's missing? Any edits? At this point, I'm going to move on to finalizing/updating template parts and template editor with more info so, between all the docs, we have everything covered.

**Comment by carolinan** [comment]
It looks good to me. I think it is ready, and if you come up with additional points, they can be added over time.
I think the length of the page is good too.

There are many things that are relevant to editing in the site editor, like using the list view, and the template part in isolation, but I believe those are covered on other pages.
For advanced users, there is also the new export feature, I'm not sure where that fits.

**Comment by annezazu** [comment]
Oohh great call. Added a section called "tools" and added in mentions of List View, patterns, and exporting. Left out template part in isolation as that will be covered for that page.

Going to ship today in [light of this convo in slack](https://wordpress.slack.com/archives/C02RP4WU5/p1641317048292100) where current links in 5.9 RC1 are broken because these are not published.

**Comment by annezazu** [comment]
Done: https://wordpress.org/support/article/site-editor/
