### ISSUE TITLE
[HelpHub]: Details Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#943]
## New page for 6.3
- [ ] Create a new article for the Details block.
- [ ] Make sure the URL slug under Permalink is: details-block
- [ ] 	At the top of the page, under the title, add the  ‘Link back to blocks’ reusable block. 

## Update for 6.3
- [ ] Remove the experimental flag and stabilize [50997](https://github.com/WordPress/gutenberg/pull/50997)
- [ ] More intuitive Details block with summary and innerBlocks content [49808](https://github.com/WordPress/gutenberg/pull/49808)
- [ ] Add Details/summary block [45055](https://github.com/WordPress/gutenberg/pull/45055)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

## Notes
1. We are not adding detailed updates for the Block settings - Typography, Color, Layout, Dimension and Border and for the More Options setting in the block toolbar. Pls mention the settings included for the block and link to the detailed settings pages instead.
2. Some of the PRs have great videos that can be added to the article.

**Comment by carolinan** [comment]
WIP: https://wordpress.org/documentation/wp-admin/post.php?post=16358117&action=edit

**Comment by femkreations** [comment]
@carolinan Is this ready for review or u still working on this one? Thanks!

**Comment by carolinan** [comment]
It is missing some images. I am still working on it.

**Comment by carolinan** [comment]
@richtabor would you like to check the description of the details block for the user documentation?

The **Details block** displays a text summary and an arrow button: When you click on the text or the button, the block opens and reveals additional content on the page.
The **summary** is customizable by selecting the "Write Summary..." placeholder text and adding your own text.
The **additional content** are blocks that you place inside the Details block. Because the content is hidden until you open the block, it is referred to as "hidden content".

**Comment by femkreations** [comment]
Thanks for working on this @carolinan I have scheduled the page to be published on Aug 8th.
